/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>test.expense_id_seq</code>
     */
    public static final Sequence<Long> EXPENSE_ID_SEQ = new SequenceImpl<Long>("expense_id_seq", Test.TEST, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
