/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects;


import javax.annotation.Generated;

import jooq.jooqobjects.tables.Expense;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.expense</code>.
     */
    public static final Expense EXPENSE = jooq.jooqobjects.tables.Expense.EXPENSE;
}
