/*
 * This file is generated by jOOQ.
*/
package jooq.jooqobjects.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Expense implements Serializable {

    private static final long serialVersionUID = -2041274639;

    private Integer    id;
    private LocalDate  date;
    private BigDecimal amount;
    private String     reason;
    private BigDecimal vat;

    public Expense() {}

    public Expense(Expense value) {
        this.id = value.id;
        this.date = value.date;
        this.amount = value.amount;
        this.reason = value.reason;
        this.vat = value.vat;
    }

    public Expense(
        Integer    id,
        LocalDate  date,
        BigDecimal amount,
        String     reason,
        BigDecimal vat
    ) {
        this.id = id;
        this.date = date;
        this.amount = amount;
        this.reason = reason;
        this.vat = vat;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDate getDate() {
        return this.date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public BigDecimal getVat() {
        return this.vat;
    }

    public void setVat(BigDecimal vat) {
        this.vat = vat;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Expense (");

        sb.append(id);
        sb.append(", ").append(date);
        sb.append(", ").append(amount);
        sb.append(", ").append(reason);
        sb.append(", ").append(vat);

        sb.append(")");
        return sb.toString();
    }
}
